#!/bin/bash

cp /nitesh/asound/asound.conf.bt /etc/asound.conf

bluealsa --profile=a2dp-source --a2dp-force-audio-cd &
sleep 5
echo -e "connect EB:06:EF:17:53:65\n" | bluetoothctl

/etc/init.d/alsa-utils restart
sleep 5
